-- Flyway baseline V1：与 2026-07 线上/本地当前库结构对齐
-- 全新空库：启动时执行本脚本建表
-- 已有非空库：baseline-on-migrate 记为已基线 V1，跳过本脚本；后续从 V2 起增量
-- 勿改已发布的 V1 内容（checksum 校验会失败）；新变更写 V2__*.sql

-- AI 对话会话表（按用户隔离）
CREATE TABLE IF NOT EXISTS chat_conversation (
    id BIGINT NOT NULL COMMENT '主键',
    user_id BIGINT NOT NULL COMMENT '所属用户ID',
    title VARCHAR(255) NOT NULL DEFAULT '新对话' COMMENT '会话标题',
    provider VARCHAR(64) COMMENT '供应商标识',
    model VARCHAR(128) COMMENT '模型ID',
    temperature DOUBLE NULL COMMENT '会话温度 0~2，空则默认 0.7',
    max_tokens INT NULL COMMENT '会话 max_tokens，空则默认 2000',
    system_prompt TEXT NULL COMMENT '会话自定义系统提示，空则用全局默认',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    INDEX idx_updated_at (updated_at),
    INDEX idx_chat_user_updated (user_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI对话会话表';

CREATE TABLE IF NOT EXISTS chat_message (
    id BIGINT NOT NULL COMMENT '主键',
    conversation_id BIGINT NOT NULL COMMENT '会话ID',
    role VARCHAR(16) NOT NULL COMMENT '角色 user/assistant',
    content TEXT NOT NULL COMMENT '消息内容',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    INDEX idx_conversation_id (conversation_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI对话消息表';

CREATE TABLE IF NOT EXISTS video_task (
    id BIGINT NOT NULL COMMENT '主键',
    user_id BIGINT COMMENT '所属用户ID',
    source_url VARCHAR(1024) NOT NULL COMMENT '源视频URL',
    title VARCHAR(512) COMMENT '视频标题',
    platform VARCHAR(32) COMMENT '平台 douyin/bilibili/youtube/xiaohongshu/other',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态含 UNDERSTANDING',
    current_step VARCHAR(128) COMMENT '当前步骤说明',
    language VARCHAR(16) DEFAULT 'zh' COMMENT '语言',
    understanding_mode VARCHAR(32) DEFAULT 'audio_only' COMMENT 'audio_only/hybrid/omni_only',
    llm_provider VARCHAR(64) COMMENT 'LLM供应商标识',
    llm_model VARCHAR(128) COMMENT 'LLM模型ID',
    omni_provider VARCHAR(64) COMMENT '多模态供应商',
    omni_model VARCHAR(128) COMMENT '多模态模型ID',
    extract_mind_map TINYINT NOT NULL DEFAULT 1 COMMENT '是否提取思维导图 1是 0否',
    generate_repurpose_script TINYINT NOT NULL DEFAULT 1 COMMENT '是否生成repurpose脚本 1是 0否',
    duration_seconds DOUBLE COMMENT '视频时长(秒)',
    video_path VARCHAR(1024) COMMENT '本地视频路径',
    audio_path VARCHAR(1024) COMMENT '本地音频路径',
    transcription_path VARCHAR(1024) COMMENT '转录JSON文件路径',
    summary_path VARCHAR(1024) COMMENT '摘要JSON文件路径',
    visual_path VARCHAR(1024) COMMENT '视觉理解JSON路径',
    transcription_json LONGTEXT COMMENT '转录结果JSON(带时间戳)',
    summary_json LONGTEXT COMMENT 'AI核心内容JSON',
    visual_json LONGTEXT COMMENT '视觉理解JSON',
    result_json LONGTEXT COMMENT '完整结构化结果JSON',
    error_message TEXT COMMENT '错误信息',
    degraded TINYINT DEFAULT 0 COMMENT '是否降级成功',
    degrade_reason VARCHAR(512) COMMENT '降级原因',
    download_duration_ms BIGINT COMMENT '下载步骤耗时(毫秒)',
    transcribe_duration_ms BIGINT COMMENT '转录步骤耗时(毫秒)',
    understand_duration_ms BIGINT COMMENT '画面理解耗时(毫秒)',
    summarize_duration_ms BIGINT COMMENT '总结步骤耗时(毫秒)',
    total_duration_ms BIGINT COMMENT '全流程总耗时(毫秒)',
    started_at DATETIME(3) COMMENT '开始处理时间',
    finished_at DATETIME(3) COMMENT '完成时间',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    INDEX idx_status (status),
    INDEX idx_platform (platform),
    INDEX idx_user_id (user_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频处理任务表';

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT NOT NULL COMMENT '主键',
    email VARCHAR(128) NOT NULL COMMENT '邮箱/用户名',
    password_hash VARCHAR(100) NOT NULL COMMENT 'BCrypt密码哈希',
    nickname VARCHAR(64) COMMENT '昵称',
    role VARCHAR(32) NOT NULL DEFAULT 'USER' COMMENT 'USER普通/MEMBER会员/SUPER_ADMIN超管',
    member_expire_at DATETIME(3) NULL COMMENT '会员到期时间，过期后仍保留展示',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1正常 0禁用',
    email_verified TINYINT NOT NULL DEFAULT 0 COMMENT '1已验证',
    last_login_at DATETIME(3) COMMENT '最后登录时间',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_email (email),
    INDEX idx_role (role),
    INDEX idx_sys_user_member_expire (member_expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS email_code (
    id BIGINT NOT NULL COMMENT '主键',
    email VARCHAR(128) NOT NULL COMMENT '邮箱',
    code VARCHAR(16) NOT NULL COMMENT '验证码',
    purpose VARCHAR(32) NOT NULL COMMENT 'REGISTER/RESET_PASSWORD',
    expires_at DATETIME(3) NOT NULL COMMENT '过期时间',
    used TINYINT NOT NULL DEFAULT 0 COMMENT '0未使用 1已使用',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    INDEX idx_email_purpose (email, purpose),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='邮箱验证码表';

CREATE TABLE IF NOT EXISTS ai_model_config (
    id BIGINT NOT NULL COMMENT '主键',
    provider VARCHAR(64) NOT NULL COMMENT '供应商标识，对应 ai.providers 的 key',
    model_id VARCHAR(128) NOT NULL COMMENT 'API模型ID',
    model_name VARCHAR(128) NOT NULL COMMENT '展示名称',
    capability VARCHAR(32) NOT NULL DEFAULT 'chat' COMMENT '能力 chat | image | video_omni',
    invoke_url VARCHAR(512) NULL COMMENT '生图 GenAI URL（image 用）',
    default_steps INT NULL COMMENT '生图默认步数',
    max_steps INT NULL COMMENT '生图最大步数',
    protocol VARCHAR(64) NULL COMMENT '生图协议，当前仅 nvidia-flux',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用 1是 0否',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序，越小越靠前',
    remark VARCHAR(255) COMMENT '备注',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_provider_model_cap (provider, model_id, capability),
    INDEX idx_cap_enabled_sort (capability, enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI模型配置表（chat/image）';

CREATE TABLE IF NOT EXISTS aigen_task (
    id                   BIGINT        NOT NULL COMMENT '主键 snowflake',
    user_id              BIGINT        NOT NULL COMMENT '所属用户',
    title                VARCHAR(256)           COMMENT '标题',
    prompt               TEXT          NOT NULL COMMENT '用户原始提示词',
    negative_prompt      VARCHAR(1024)          COMMENT '负向约束',
    template_id          VARCHAR(64)   NOT NULL COMMENT '模板 ID',
    pipeline_mode        VARCHAR(16)   DEFAULT 'template' COMMENT 'template|visual',
    audio_mode           VARCHAR(16)            COMMENT 'none|bgm_only|tts',
    style_preset         VARCHAR(64)            COMMENT '风格预设',
    shot_count           INT                    COMMENT '镜头数',
    asset_done_count     INT                    COMMENT '已完成素材镜数',
    status               VARCHAR(32)   NOT NULL DEFAULT 'PENDING' COMMENT '状态',
    current_step         VARCHAR(128)           COMMENT '当前步骤说明',
    progress             INT           NOT NULL DEFAULT 0 COMMENT '0-100',
    language             VARCHAR(16)   DEFAULT 'zh',
    aspect_ratio         VARCHAR(16)   DEFAULT '9:16',
    target_duration_sec  INT           DEFAULT 30,
    style_json           JSON                   COMMENT '主题色/字体等',
    voice_id             VARCHAR(64),
    bgm_id               VARCHAR(64),
    llm_provider         VARCHAR(64),
    llm_model            VARCHAR(128),
    image_provider       VARCHAR(64)            COMMENT '生图供应商',
    image_model          VARCHAR(128)           COMMENT '生图模型 ID',
    storyboard_json      LONGTEXT,
    storyboard_path      VARCHAR(1024),
    work_dir             VARCHAR(1024),
    output_path          VARCHAR(1024),
    poster_path          VARCHAR(1024),
    output_size_bytes    BIGINT,
    duration_seconds     DOUBLE,
    error_message        TEXT,
    plan_duration_ms     BIGINT,
    asset_duration_ms    BIGINT,
    render_duration_ms   BIGINT,
    total_duration_ms    BIGINT,
    started_at           DATETIME(3),
    finished_at          DATETIME(3),
    created_at           DATETIME(3)   NOT NULL,
    updated_at           DATETIME(3)   NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_aigen_user_created (user_id, created_at),
    INDEX idx_aigen_status (status),
    INDEX idx_aigen_template (template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI视频生成任务';

CREATE TABLE IF NOT EXISTS imggen_task (
    id                    BIGINT         NOT NULL COMMENT '主键 snowflake',
    user_id               BIGINT         NOT NULL COMMENT '所属用户',
    title                 VARCHAR(256)            COMMENT '标题',
    prompt                TEXT           NOT NULL COMMENT '用户原始提示词',
    enhanced_prompt       TEXT                    COMMENT '润色后提示词',
    negative_prompt       VARCHAR(1024)           COMMENT '负向提示词',
    status                VARCHAR(32)    NOT NULL DEFAULT 'PENDING' COMMENT '状态',
    current_step          VARCHAR(128)            COMMENT '当前步骤说明',
    progress              INT            NOT NULL DEFAULT 0 COMMENT '0-100',
    provider              VARCHAR(64)             COMMENT '生图供应商 key',
    model                 VARCHAR(128)            COMMENT '生图模型路径',
    aspect_ratio          VARCHAR(16)             COMMENT '1:1 / 16:9 / 9:16',
    width                 INT                     COMMENT '像素宽',
    height                INT                     COMMENT '像素高',
    steps                 INT                     COMMENT '扩散步数',
    n                     INT            DEFAULT 1 COMMENT '张数',
    seed                  BIGINT         NULL     COMMENT '随机种子',
    enhance_enabled       TINYINT        DEFAULT 0 COMMENT '是否启用 prompt 润色',
    llm_provider          VARCHAR(64)             COMMENT '润色用 LLM 供应商',
    llm_model             VARCHAR(128)            COMMENT '润色用 LLM 模型',
    result_json           LONGTEXT                COMMENT '多图元数据 JSON',
    work_dir              VARCHAR(1024),
    cover_path            VARCHAR(1024)           COMMENT '封面/首图绝对路径',
    error_message         TEXT,
    provider_request_id   VARCHAR(128),
    enhance_duration_ms   BIGINT,
    generate_duration_ms  BIGINT,
    total_duration_ms     BIGINT,
    started_at            DATETIME(3),
    finished_at           DATETIME(3),
    created_at            DATETIME(3)    NOT NULL,
    updated_at            DATETIME(3)    NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_imggen_user_created (user_id, created_at),
    INDEX idx_imggen_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI文生图任务';

CREATE TABLE IF NOT EXISTS member_plan (
    id                    BIGINT         NOT NULL COMMENT '主键 snowflake',
    code                  VARCHAR(64)    NOT NULL COMMENT 'month/quarter/year',
    name                  VARCHAR(128)   NOT NULL,
    description           VARCHAR(512)            ,
    duration_days         INT            NOT NULL COMMENT '应用层校验 >0',
    price_cents           INT            NOT NULL COMMENT '分；应用层校验 >0',
    original_price_cents  INT                     ,
    currency              VARCHAR(8)     NOT NULL DEFAULT 'CNY',
    status                TINYINT        NOT NULL DEFAULT 1 COMMENT '1上架 0下架',
    sort_order            INT            NOT NULL DEFAULT 0,
    created_at            DATETIME(3)    NOT NULL,
    updated_at            DATETIME(3)    NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_member_plan_code (code),
    INDEX idx_member_plan_status_sort (status, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会员套餐';

CREATE TABLE IF NOT EXISTS pay_order (
    id                    BIGINT         NOT NULL,
    order_no              VARCHAR(32)    NOT NULL COMMENT 'out_trade_no',
    user_id               BIGINT         NOT NULL,
    plan_id               BIGINT         NOT NULL,
    plan_code             VARCHAR(64)    NOT NULL,
    plan_name             VARCHAR(128)   NOT NULL,
    duration_days         INT            NOT NULL,
    channel               VARCHAR(16)    NOT NULL COMMENT 'alipay/wechat/mock',
    client_type           VARCHAR(8)     NOT NULL DEFAULT 'PC',
    amount_cents          INT            NOT NULL,
    currency              VARCHAR(8)     NOT NULL DEFAULT 'CNY',
    status                VARCHAR(16)    NOT NULL DEFAULT 'CREATED',
    fulfilled             TINYINT        NOT NULL DEFAULT 0,
    trade_no              VARCHAR(64)             ,
    prepay_id             VARCHAR(128)            ,
    code_url              VARCHAR(512)            ,
    pay_url               VARCHAR(1024)           ,
    channel_extra_json    TEXT                    ,
    client_ip             VARCHAR(64)             ,
    expire_at             DATETIME(3)    NOT NULL,
    paid_at               DATETIME(3)             ,
    closed_at             DATETIME(3)             ,
    close_reason          VARCHAR(64)             ,
    refund_status         VARCHAR(16)             COMMENT '标记用 NONE/SUCCESS 等',
    refund_amount_cents   INT                     ,
    version               INT            NOT NULL DEFAULT 0,
    created_at            DATETIME(3)    NOT NULL,
    updated_at            DATETIME(3)    NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_pay_order_no (order_no),
    INDEX idx_pay_user_created (user_id, created_at),
    INDEX idx_pay_status_expire (status, expire_at),
    INDEX idx_pay_status_fulfilled (status, fulfilled, updated_at),
    INDEX idx_pay_trade_no (trade_no),
    INDEX idx_pay_channel_status (channel, status),
    UNIQUE KEY uk_pay_channel_trade (channel, trade_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付订单';

CREATE TABLE IF NOT EXISTS pay_notify_log (
    id                    BIGINT         NOT NULL,
    order_no              VARCHAR(32)             ,
    channel               VARCHAR(16)    NOT NULL,
    notify_id             VARCHAR(128)            ,
    body_raw              MEDIUMTEXT              ,
    headers_json          TEXT                    ,
    verify_ok             TINYINT        NOT NULL DEFAULT 0,
    process_result        VARCHAR(32)    NOT NULL,
    error_message         VARCHAR(512)            ,
    created_at            DATETIME(3)    NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_notify_order (order_no),
    INDEX idx_notify_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付异步通知日志';

CREATE TABLE IF NOT EXISTS kb_category (
    id          BIGINT       NOT NULL COMMENT '主键',
    user_id     BIGINT       NOT NULL COMMENT '所属用户',
    name        VARCHAR(64)  NOT NULL COMMENT '分类名',
    parent_id   BIGINT       NULL COMMENT '父分类，NULL 为根',
    sort_order  INT          NOT NULL DEFAULT 0 COMMENT '同级排序，小在前',
    created_at  DATETIME(3)  NOT NULL COMMENT '创建时间',
    updated_at  DATETIME(3)  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    INDEX idx_kb_cat_user_parent (user_id, parent_id),
    INDEX idx_kb_cat_user_sort (user_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库分类';

CREATE TABLE IF NOT EXISTS kb_tag (
    id          BIGINT       NOT NULL COMMENT '主键',
    user_id     BIGINT       NOT NULL COMMENT '所属用户',
    name        VARCHAR(64)  NOT NULL COMMENT '标签名',
    created_at  DATETIME(3)  NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_tag_user_name (user_id, name),
    INDEX idx_kb_tag_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库标签';

CREATE TABLE IF NOT EXISTS kb_note (
    id             BIGINT        NOT NULL COMMENT '主键',
    user_id        BIGINT        NOT NULL COMMENT '所属用户',
    title          VARCHAR(200)  NOT NULL DEFAULT '' COMMENT '标题',
    content        LONGTEXT      NULL COMMENT '正文（markdown 或 html）',
    content_format VARCHAR(16)   NOT NULL DEFAULT 'markdown' COMMENT 'html|markdown',
    snippet        VARCHAR(512)  NULL COMMENT '列表摘要（纯文本）',
    category_id    BIGINT        NULL COMMENT '文件夹，可空',
    sort_order     INT           NOT NULL DEFAULT 0 COMMENT '同文件夹内排序，小在前',
    is_pinned      TINYINT       NOT NULL DEFAULT 0 COMMENT '置顶 0/1',
    is_deleted     TINYINT       NOT NULL DEFAULT 0 COMMENT '软删 0/1',
    deleted_at     DATETIME(3)   NULL COMMENT '软删时间',
    share_token    VARCHAR(64)   NULL COMMENT '公开分享令牌',
    share_enabled  TINYINT       NOT NULL DEFAULT 0 COMMENT '是否开启分享 0/1',
    share_enabled_at DATETIME(3) NULL COMMENT '开启分享时间',
    created_at     DATETIME(3)   NOT NULL COMMENT '创建时间',
    updated_at     DATETIME(3)   NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_kb_note_share_token (share_token),
    INDEX idx_kb_note_user_updated (user_id, is_deleted, updated_at),
    INDEX idx_kb_note_user_cat (user_id, category_id, is_deleted),
    INDEX idx_kb_note_user_cat_sort (user_id, category_id, is_deleted, sort_order),
    INDEX idx_kb_note_user_pinned (user_id, is_pinned, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库笔记';

CREATE TABLE IF NOT EXISTS kb_note_tag (
    note_id BIGINT NOT NULL COMMENT '笔记ID',
    tag_id  BIGINT NOT NULL COMMENT '标签ID',
    PRIMARY KEY (note_id, tag_id),
    INDEX idx_kb_note_tag_tag (tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记标签关联';

CREATE TABLE IF NOT EXISTS kb_file (
    id             BIGINT        NOT NULL COMMENT '主键',
    user_id        BIGINT        NOT NULL COMMENT '所属用户',
    note_id        BIGINT        NULL COMMENT '关联笔记，可空',
    original_name  VARCHAR(255)  NOT NULL COMMENT '原始文件名',
    content_type   VARCHAR(128)  NULL COMMENT 'MIME',
    size_bytes     BIGINT        NOT NULL DEFAULT 0 COMMENT '字节数',
    object_key     VARCHAR(512)  NOT NULL COMMENT '对象存储 key',
    kind           VARCHAR(32)   NOT NULL DEFAULT 'other' COMMENT 'image|video|audio|pdf|office|other',
    created_at     DATETIME(3)   NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    INDEX idx_kb_file_user_note (user_id, note_id),
    INDEX idx_kb_file_user_created (user_id, created_at),
    UNIQUE KEY uk_kb_file_object_key (object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库附件';

-- 文章/新闻提取（原 doc/sql/article_task.sql，此前未并入 schema.sql）
CREATE TABLE IF NOT EXISTS article_task (
    id                    BIGINT         NOT NULL COMMENT '主键 snowflake',
    user_id               BIGINT         NOT NULL COMMENT '所属用户',
    source_url            VARCHAR(2048)           COMMENT '源链接，可空（纯粘贴）',
    canonical_url         VARCHAR(2048)           COMMENT '规范化/跳转后 URL',
    platform              VARCHAR(32)             COMMENT 'generic/zhihu/weibo/x/weixin/xiaohongshu/toutiao/bilibili_column/other',
    support_level         VARCHAR(16)             COMMENT 'FULL/PARTIAL/PASTE_ONLY/UNSUPPORTED',
    title                 VARCHAR(512)            COMMENT '标题',
    author                VARCHAR(256)            COMMENT '作者',
    status                VARCHAR(32)    NOT NULL DEFAULT 'PENDING',
    current_step          VARCHAR(128),
    progress              INT            NOT NULL DEFAULT 0,
    language              VARCHAR(16)    DEFAULT 'zh',
    input_mode            VARCHAR(16)    NOT NULL DEFAULT 'url' COMMENT 'url|paste|url_and_paste',
    paste_text            MEDIUMTEXT              COMMENT '用户粘贴正文，应用层 max 100000 chars',
    main_text             MEDIUMTEXT              COMMENT '正文截断副本（应用层截断）；全文见 main_text_path',
    main_text_chars       INT                     COMMENT '全文字符数（截断前）',
    force_paste_only      TINYINT        DEFAULT 0 COMMENT '1=跳过 FETCH 强制用 paste',
    allow_paste_fallback  TINYINT        DEFAULT 1 COMMENT '1=抓取失败可 NEEDS_PASTE',
    paste_resume          TINYINT        DEFAULT 0 COMMENT '单轮标志：仅 /paste 入队置1；pipeline 消费后立即清0；retry 强制0',
    llm_provider          VARCHAR(64),
    llm_model             VARCHAR(128),
    extract_mind_map      TINYINT        DEFAULT 0,
    generate_rewrite      TINYINT        DEFAULT 1,
    rewrite_variants      VARCHAR(512)            COMMENT 'JSON array of variant ids',
    request_options_json  TEXT                    COMMENT '创建时 options 快照 JSON，便于审计',
    core_json             LONGTEXT,
    rewrite_json          LONGTEXT,
    result_json           LONGTEXT,
    raw_html_path         VARCHAR(1024),
    main_text_path        VARCHAR(1024)           COMMENT '全文对象存储 key/path',
    error_code            VARCHAR(64),
    error_message         TEXT,
    degraded              TINYINT        DEFAULT 0,
    degrade_reason        VARCHAR(512),
    quality_score         DOUBLE,
    resolve_duration_ms   BIGINT,
    fetch_duration_ms     BIGINT,
    extract_duration_ms   BIGINT,
    core_duration_ms      BIGINT,
    rewrite_duration_ms   BIGINT,
    total_duration_ms     BIGINT,
    work_dir              VARCHAR(1024),
    started_at            DATETIME(3),
    finished_at           DATETIME(3),
    created_at            DATETIME(3)    NOT NULL COMMENT '应用写入',
    updated_at            DATETIME(3)    NOT NULL COMMENT '应用写入',
    PRIMARY KEY (id),
    INDEX idx_article_user_created (user_id, created_at),
    INDEX idx_article_status (status),
    INDEX idx_article_platform (platform)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文章/新闻提取任务';
