package com.dwcode.okxbot.auth.mail;

import com.dwcode.okxbot.auth.config.AuthProperties;
import com.dwcode.okxbot.common.exception.BusinessException;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.Call;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Protocol;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class AgentMailClientTest {

    private AuthProperties props;
    private OkHttpClient httpClient;
    private Call call;
    private AgentMailClient client;

    @BeforeEach
    void setUp() {
        props = new AuthProperties();
        props.getMail().getAgentmail().setApiKey("am_test_key");
        props.getMail().getAgentmail().setInboxId("inbox_abc");
        props.getMail().getAgentmail().setBaseUrl("https://api.agentmail.to");

        httpClient = mock(OkHttpClient.class);
        call = mock(Call.class);
        when(httpClient.newCall(any(Request.class))).thenReturn(call);

        client = new AgentMailClient(props, new ObjectMapper(), httpClient);
    }

    @Test
    void sendText_postsToSendEndpointWithBearer() throws Exception {
        when(call.execute()).thenReturn(jsonResponse(200,
                "{\"message_id\":\"m1\",\"thread_id\":\"t1\"}"));

        client.sendText("user@example.com", "验证码", "您的验证码是：123456");

        ArgumentCaptor<Request> captor = ArgumentCaptor.forClass(Request.class);
        verify(httpClient).newCall(captor.capture());
        Request req = captor.getValue();

        assertEquals("POST", req.method());
        assertEquals("https://api.agentmail.to/v0/inboxes/inbox_abc/messages/send",
                req.url().toString());
        assertEquals("Bearer am_test_key", req.header("Authorization"));
        assertTrue(req.header("Idempotency-Key") != null && !req.header("Idempotency-Key").isBlank());

        okio.Buffer buffer = new okio.Buffer();
        req.body().writeTo(buffer);
        String body = buffer.readUtf8();
        assertTrue(body.contains("\"to\":\"user@example.com\""));
        assertTrue(body.contains("\"subject\":\"验证码\""));
        assertTrue(body.contains("123456"));
    }

    @Test
    void sendText_missingConfig_throws() {
        props.getMail().getAgentmail().setApiKey("");
        assertThrows(BusinessException.class,
                () -> client.sendText("a@b.com", "s", "t"));
    }

    @Test
    void sendText_httpError_throwsBusiness() throws Exception {
        when(call.execute()).thenReturn(jsonResponse(403,
                "{\"code\":\"missing_permission\",\"message\":\"no send\"}"));

        BusinessException ex = assertThrows(BusinessException.class,
                () -> client.sendText("a@b.com", "s", "t"));
        assertTrue(ex.getMessage().contains("鉴权") || ex.getMessage().contains("权限"));
    }

    @Test
    void mapHttpError_cloudFrontHtml_givesNetworkHint() {
        String html = "<HTML><H1>403 ERROR</H1>Request blocked. Generated by cloudfront (CloudFront)</HTML>";
        String msg = AgentMailClient.mapHttpError(403, html, new ObjectMapper());
        assertTrue(msg.contains("CloudFront"));
        assertTrue(msg.contains("proxy") || msg.contains("smtp") || msg.contains("部署"));
    }

    @Test
    void buildHttpClient_withProxy_configuresOkHttp() {
        AuthProperties p = new AuthProperties();
        p.getMail().getAgentmail().setProxyHost("127.0.0.1");
        p.getMail().getAgentmail().setProxyPort(7897);
        p.getMail().getAgentmail().setProxyType("HTTP");
        OkHttpClient client = AgentMailClient.buildHttpClient(p);
        assertEquals(java.net.Proxy.Type.HTTP, client.proxy().type());
        assertEquals(7897, ((java.net.InetSocketAddress) client.proxy().address()).getPort());
    }

    private static Response jsonResponse(int code, String body) {
        return new Response.Builder()
                .request(new Request.Builder().url("https://api.agentmail.to/v0/inboxes/x/messages/send").build())
                .protocol(Protocol.HTTP_1_1)
                .code(code)
                .message(code == 200 ? "OK" : "ERR")
                .body(ResponseBody.create(body, MediaType.get("application/json")))
                .build();
    }
}
