#!/usr/bin/env bash
# Cloudflare Named Tunnel（固定域名）
#
# 前置: 域名已接入 Cloudflare DNS
#
# 流程:
#   1) bash deploy/scripts/named-tunnel.sh login
#      → 打开打印的 URL，在浏览器选择你的域名并授权
#   2) bash deploy/scripts/named-tunnel.sh setup app.example.com
#      → 创建隧道 + DNS CNAME + 写配置 + 启动
#   3) bash deploy/scripts/named-tunnel.sh status
#
# 其它:
#   stop | restart | logs | url
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
APP_DIR="$(pwd -P)"

COMPOSE_REL="${COMPOSE_FILE:-deploy/stack/compose.lite.yml}"
ENV_REL="deploy/env/app.env"
[[ -f "$ENV_REL" ]] || ENV_REL="deploy/.env"

# 宿主机凭据目录（gitignore）
CF_DIR="${CLOUDFLARED_DIR:-$APP_DIR/deploy/env/cloudflared}"
CF_HOME="${CLOUDFLARED_HOME:-$HOME/.cloudflared}"
TUNNEL_NAME="${TUNNEL_NAME:-auto-exchange}"

write_tunnel_override() {
  # cloudflared 无 shell：用 compose override 挂载凭据并 run named
  mkdir -p "$CF_DIR"
  cat > "$CF_DIR/tunnel.override.yml" <<EOF
services:
  tunnel:
    command:
      - tunnel
      - --no-autoupdate
      - --config
      - /etc/cloudflared/config.yml
      - run
    volumes:
      - ${CF_DIR}:/etc/cloudflared:ro
EOF
}

compose() {
  write_tunnel_override
  local args=(-f "$COMPOSE_REL" -f "$CF_DIR/tunnel.override.yml" --profile tunnel)
  [[ -f "$ENV_REL" ]] && args+=(--env-file "$ENV_REL")
  docker compose "${args[@]}" "$@"
}

need_cloudflared() {
  if command -v cloudflared >/dev/null 2>&1; then
    return 0
  fi
  echo "==> 安装 cloudflared（主机 CLI，用于 login/create）"
  local arch
  arch=$(uname -m)
  local deb=cloudflared-linux-amd64.deb
  [[ "$arch" == "aarch64" || "$arch" == "arm64" ]] && deb=cloudflared-linux-arm64.deb
  curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/${deb}" -o /tmp/cloudflared.deb
  sudo dpkg -i /tmp/cloudflared.deb
  cloudflared --version
}

cmd_login() {
  need_cloudflared
  mkdir -p "$CF_HOME"
  echo ""
  echo "=========================================="
  echo " 下一步会打印一个 Cloudflare 授权链接"
  echo " 请在浏览器打开 → 选择你的域名 → Authorize"
  echo " 授权完成后本命令会自动结束"
  echo "=========================================="
  echo ""
  # 非交互：若已有 cert 则跳过
  if [[ -f "$CF_HOME/cert.pem" ]]; then
    echo "已存在 $CF_HOME/cert.pem ，如需重登: rm $CF_HOME/cert.pem 后再 login"
    return 0
  fi
  cloudflared tunnel login
  echo "login OK: $CF_HOME/cert.pem"
}

cmd_setup() {
  local hostname="${1:-}"
  if [[ -z "$hostname" ]]; then
    echo "用法: $0 setup <固定域名FQDN>" >&2
    echo "例:   $0 setup app.example.com" >&2
    exit 1
  fi
  need_cloudflared
  if [[ ! -f "$CF_HOME/cert.pem" ]]; then
    echo "ERROR: 尚未 login。先执行: $0 login" >&2
    exit 1
  fi

  mkdir -p "$CF_DIR"
  chmod 700 "$CF_DIR"

  # 创建或复用隧道
  local tunnel_id=""
  if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
    echo "==> 隧道已存在: $TUNNEL_NAME"
    tunnel_id=$(cloudflared tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')
  else
    echo "==> 创建隧道: $TUNNEL_NAME"
    # 输出类似: Created tunnel auto-exchange with id xxxx-xxxx
    local out
    out=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
    echo "$out"
    tunnel_id=$(echo "$out" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
  fi
  if [[ -z "$tunnel_id" ]]; then
    tunnel_id=$(cloudflared tunnel list | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')
  fi
  if [[ -z "$tunnel_id" ]]; then
    echo "ERROR: 无法解析 tunnel id" >&2
    cloudflared tunnel list || true
    exit 1
  fi
  echo "tunnel_id=$tunnel_id"

  # 凭据 json 默认在 ~/.cloudflared/<id>.json
  local cred_src="$CF_HOME/${tunnel_id}.json"
  if [[ ! -f "$cred_src" ]]; then
    echo "ERROR: 找不到凭据 $cred_src" >&2
    ls -la "$CF_HOME" || true
    exit 1
  fi
  cp -a "$cred_src" "$CF_DIR/${tunnel_id}.json"
  chmod 600 "$CF_DIR/${tunnel_id}.json"

  # DNS 路由（在 Cloudflare 建 CNAME → <id>.cfargotunnel.com）
  echo "==> DNS: $hostname → tunnel $TUNNEL_NAME"
  cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$hostname" || \
    cloudflared tunnel route dns "$TUNNEL_NAME" "$hostname"

  # 写 config.yml（容器内路径）
  cat > "$CF_DIR/config.yml" <<EOF
# generated by named-tunnel.sh — do not commit
tunnel: ${tunnel_id}
credentials-file: /etc/cloudflared/${tunnel_id}.json

ingress:
  - hostname: ${hostname}
    service: http://web:80
  - service: http_status:404
EOF
  chmod 600 "$CF_DIR/config.yml"

  # 记录
  echo "$hostname" > "$CF_DIR/hostname"
  echo "$tunnel_id" > "$CF_DIR/tunnel-id"
  echo "https://${hostname}" > "$CF_DIR/public-url"
  echo "https://${hostname}" | sudo tee /data/auto-exchange/named-tunnel.url >/dev/null 2>&1 || true

  # 标记使用 named 模式
  echo "named" > "$CF_DIR/mode"

  echo "==> 切换 compose 到 Named Tunnel 并启动"
  # 停掉 quick tunnel（同一 service 名 tunnel）
  compose stop tunnel 2>/dev/null || true
  compose rm -f tunnel 2>/dev/null || true
  compose up -d --no-deps tunnel

  echo ""
  echo "=========================================="
  echo "  固定域名已配置"
  echo "  https://${hostname}"
  echo "=========================================="
  echo ""
  echo "DNS 生效可能需 1–5 分钟。检测:"
  echo "  curl -sI https://${hostname}/ | head"
  echo ""
  echo "建议把 app.env 中 PAY_PUBLIC_BASE_URL 改为:"
  echo "  PAY_PUBLIC_BASE_URL=https://${hostname}"
  echo "然后本机: sync-env-local.ps1"
  sleep 3
  compose ps tunnel || true
  compose logs --tail=30 tunnel || true
}

cmd_start() {
  if [[ ! -f "$CF_DIR/config.yml" ]]; then
    echo "ERROR: 未 setup。用法: $0 setup <hostname>" >&2
    exit 1
  fi
  echo "named" > "$CF_DIR/mode"
  compose up -d --no-deps tunnel
  compose ps tunnel
  cmd_url
}

cmd_stop() {
  compose stop tunnel 2>/dev/null || true
  compose rm -f tunnel 2>/dev/null || true
  echo "tunnel stopped"
}

cmd_restart() {
  compose up -d --no-deps --force-recreate tunnel
  compose ps tunnel
  cmd_url
}

cmd_url() {
  if [[ -f "$CF_DIR/public-url" ]]; then
    cat "$CF_DIR/public-url"
  elif [[ -f "$CF_DIR/hostname" ]]; then
    echo "https://$(cat "$CF_DIR/hostname")"
  else
    echo "尚未 setup 固定域名" >&2
    exit 1
  fi
  compose ps tunnel 2>/dev/null || true
}

cmd_status() {
  echo "mode: $(cat "$CF_DIR/mode" 2>/dev/null || echo unknown)"
  echo "hostname: $(cat "$CF_DIR/hostname" 2>/dev/null || echo -)"
  echo "tunnel-id: $(cat "$CF_DIR/tunnel-id" 2>/dev/null || echo -)"
  echo "config: $CF_DIR/config.yml"
  [[ -f "$CF_DIR/config.yml" ]] && cat "$CF_DIR/config.yml"
  echo "---"
  compose ps tunnel 2>/dev/null || true
  compose logs --tail=20 tunnel 2>/dev/null || true
  if command -v cloudflared >/dev/null 2>&1; then
    echo "--- tunnel list ---"
    cloudflared tunnel list 2>/dev/null || true
  fi
}

cmd_logs() {
  compose logs -f --tail=80 tunnel
}

cmd="${1:-}"
case "$cmd" in
  login)   cmd_login ;;
  setup)   shift; cmd_setup "${1:-}" ;;
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  url)     cmd_url ;;
  status)  cmd_status ;;
  logs)    cmd_logs ;;
  *)
    cat <<'EOF'
用法:
  named-tunnel.sh login                 # 浏览器授权 Cloudflare 域名
  named-tunnel.sh setup <fqdn>          # 创建固定隧道 + DNS + 启动
  named-tunnel.sh start|stop|restart
  named-tunnel.sh url|status|logs

例:
  bash deploy/scripts/named-tunnel.sh login
  bash deploy/scripts/named-tunnel.sh setup app.yourdomain.com
EOF
    exit 1
    ;;
esac
