package com.dwcode.okxbot.video.service;

import com.dwcode.okxbot.common.exception.BusinessException;
import com.dwcode.okxbot.video.config.VideoProperties;
import com.dwcode.okxbot.video.dto.VideoCookieStatusResponse;
import com.dwcode.okxbot.video.dto.VideoCookieUploadRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * 抖音等平台 Cookie 管理：把浏览器 Cookie 请求头写成 yt-dlp Netscape cookies.txt。
 * <p>文件为<strong>服务端全局</strong>配置（与 application.yml cookies-file 同一路径），
 * 供本机 yt-dlp 下载使用；不按用户隔离。
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class VideoCookieService {

    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private final VideoProperties videoProperties;

    public VideoCookieStatusResponse status(String platform) {
        String p = normalizePlatform(platform);
        Path path = resolveCookiePath(p);
        boolean exists = Files.isRegularFile(path);
        Integer count = null;
        Long size = null;
        String modified = null;
        if (exists) {
            try {
                size = Files.size(path);
                modified = LocalDateTime.ofInstant(
                        Instant.ofEpochMilli(Files.getLastModifiedTime(path).toMillis()),
                        ZoneId.systemDefault()).format(DT);
                count = countCookieLines(path);
            } catch (IOException e) {
                log.warn("读取 cookie 文件状态失败: {}", e.getMessage());
            }
        }
        boolean ymlConfigured = videoProperties.getDownload().getCookiesFile() != null
                && !videoProperties.getDownload().getCookiesFile().isBlank();
        return VideoCookieStatusResponse.builder()
                .platform(p)
                .configured(ymlConfigured || exists)
                .fileExists(exists)
                // 不向客户端暴露宿主机绝对路径
                .filePath(null)
                .cookieCount(count)
                .fileSizeBytes(size)
                .lastModifiedAt(modified)
                .hint(exists
                        ? "已配置 Cookie。过期后重新上传即可（无需改 yml）。"
                        : "尚未上传。请在抖音网页 F12 复制 Cookie 后粘贴上传。")
                .build();
    }

    public VideoCookieStatusResponse upload(VideoCookieUploadRequest request) {
        String platform = normalizePlatform(request.getPlatform());
        String header = request.getCookieHeader() != null ? request.getCookieHeader().trim() : "";
        if (header.isEmpty()) {
            throw new BusinessException(400, "Cookie 不能为空");
        }
        if (header.toLowerCase(Locale.ROOT).startsWith("cookie:")) {
            header = header.substring(7).trim();
        }

        String domain = domainForPlatform(platform);
        List<String[]> pairs = parseCookieHeader(header);
        if (pairs.isEmpty()) {
            throw new BusinessException(400, "未能解析出 name=value Cookie 对，请粘贴完整 Cookie 请求头");
        }

        Path path = resolveCookiePath(platform);
        try {
            Path parent = path.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            long expires = Instant.now().getEpochSecond() + 180L * 24 * 3600;
            StringBuilder sb = new StringBuilder();
            sb.append("# Netscape HTTP Cookie File\n");
            sb.append("# Generated by VideoCookieService\n");
            sb.append("# platform=").append(platform).append(" domain=").append(domain).append('\n');
            sb.append('\n');
            String includeSub = domain.startsWith(".") ? "TRUE" : "FALSE";
            for (String[] pair : pairs) {
                // domain \t flag \t path \t secure \t expires \t name \t value
                sb.append(domain).append('\t')
                        .append(includeSub).append('\t')
                        .append('/').append('\t')
                        .append("TRUE").append('\t')
                        .append(expires).append('\t')
                        .append(pair[0]).append('\t')
                        .append(pair[1]).append('\n');
            }
            Files.writeString(path, sb.toString(), StandardCharsets.UTF_8);

            // 运行时指向该文件，避免 yml 未写 cookies-file 时仍无效
            videoProperties.getDownload().setCookiesFile(path.toAbsolutePath().toString());
            // from-browser 与 file 冲突时 file 优先（DownloadService 已实现）

            log.info("已写入 Cookie 文件: platform={}, count={}, path={}",
                    platform, pairs.size(), path.toAbsolutePath());
        } catch (IOException e) {
            throw new BusinessException("写入 Cookie 文件失败: " + e.getMessage());
        }
        return status(platform);
    }

    public void clear(String platform) {
        String p = normalizePlatform(platform);
        Path path = resolveCookiePath(p);
        try {
            if (Files.deleteIfExists(path)) {
                log.info("已删除 Cookie 文件: {}", path);
            }
        } catch (IOException e) {
            throw new BusinessException("删除 Cookie 文件失败: " + e.getMessage());
        }
    }

    /**
     * 解析 Cookie 请求头为 name/value 对。
     */
    static List<String[]> parseCookieHeader(String header) {
        List<String[]> out = new ArrayList<>();
        if (header == null || header.isBlank()) {
            return out;
        }
        for (String part : header.split(";")) {
            String pair = part.trim();
            if (pair.isEmpty()) {
                continue;
            }
            int eq = pair.indexOf('=');
            if (eq <= 0) {
                continue;
            }
            String name = pair.substring(0, eq).trim();
            String value = pair.substring(eq + 1).trim();
            if (!name.isEmpty()) {
                out.add(new String[]{name, value});
            }
        }
        return out;
    }

    Path resolveCookiePath(String platform) {
        String configured = videoProperties.getDownload().getCookiesFile();
        if (configured != null && !configured.isBlank()
                && ("douyin".equals(platform) || configured.toLowerCase(Locale.ROOT).contains(platform))) {
            return Path.of(configured.trim()).toAbsolutePath().normalize();
        }
        // 默认：work-dir 同级 data 或 work-dir 下
        Path work = Path.of(videoProperties.getWorkDir()).toAbsolutePath().normalize();
        Path dataDir = work.getParent() != null ? work.getParent() : work;
        String fileName = switch (platform) {
            case "xiaohongshu" -> "xiaohongshu-cookies.txt";
            case "bilibili" -> "bilibili-cookies.txt";
            default -> "douyin-cookies.txt";
        };
        return dataDir.resolve(fileName).normalize();
    }

    private static String domainForPlatform(String platform) {
        return switch (platform) {
            case "xiaohongshu" -> ".xiaohongshu.com";
            case "bilibili" -> ".bilibili.com";
            case "tiktok" -> ".tiktok.com";
            default -> ".douyin.com";
        };
    }

    private static String normalizePlatform(String platform) {
        if (platform == null || platform.isBlank()) {
            return "douyin";
        }
        String p = platform.trim().toLowerCase(Locale.ROOT);
        return switch (p) {
            case "dy", "抖音" -> "douyin";
            case "xhs", "小红书" -> "xiaohongshu";
            case "bili", "b站" -> "bilibili";
            default -> p;
        };
    }

    private static int countCookieLines(Path path) throws IOException {
        int n = 0;
        for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
            String t = line.trim();
            if (t.isEmpty() || t.startsWith("#")) {
                continue;
            }
            n++;
        }
        return n;
    }
}
